const mongoose = require("mongoose");

// Define the Category schema directly since we're in JS
const categorySchema = new mongoose.Schema(
  {
    name: { type: String, required: true, unique: true, trim: true },
    slug: { type: String, required: true, trim: true, index: true },
    icon: { type: String, required: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true },
    sortOrder: { type: Number, default: 0 },
    subcategories: [
      {
        name: { type: String, required: true, trim: true },
        slug: { type: String, required: true, trim: true },
        description: { type: String, trim: true },
        isActive: { type: Boolean, default: true },
        sortOrder: { type: Number, default: 0 },
        customFields: [
          {
            fieldName: { type: String, required: true, trim: true },
            fieldType: {
              type: String,
              required: true,
              enum: ["text", "number", "select", "boolean", "textarea", "date"],
            },
            label: { type: String, required: true, trim: true },
            required: { type: Boolean, default: false },
            options: [{ type: String, trim: true }],
            placeholder: String,
            validation: {
              min: Number,
              max: Number,
              pattern: String,
              minLength: Number,
              maxLength: Number,
            },
          },
        ],
      },
    ],
  },
  {
    timestamps: { createdAt: "created_at", updatedAt: "updated_at" },
  }
);

// Create or get existing model
const Category =
  mongoose.models.Category || mongoose.model("Category", categorySchema);

// Comprehensive categories data for Liberian marketplace
const initialCategories = [
  {
    name: "Electronics",
    slug: "electronics",
    icon: "📱",
    description: "Mobile phones, computers, and electronic devices",
    sortOrder: 1,
    isActive: true,
    subcategories: [
      {
        name: "Mobile Phones",
        slug: "mobile-phones",
        description: "Smartphones and feature phones",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "brand",
            fieldType: "select",
            label: "Brand",
            required: true,
            options: [
              "Apple",
              "Samsung",
              "Huawei",
              "Xiaomi",
              "Tecno",
              "Infinix",
              "Itel",
              "Nokia",
              "Oppo",
              "Vivo",
              "Other",
            ],
          },
          {
            fieldName: "model",
            fieldType: "text",
            label: "Model",
            required: true,
            placeholder: "e.g. iPhone 13 Pro, Galaxy S21",
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
          {
            fieldName: "storage",
            fieldType: "select",
            label: "Storage",
            options: ["16GB", "32GB", "64GB", "128GB", "256GB", "512GB", "1TB"],
          },
          {
            fieldName: "network",
            fieldType: "select",
            label: "Network",
            options: ["2G", "3G", "4G LTE", "5G"],
          },
        ],
      },
      {
        name: "Tablets",
        slug: "tablets",
        description: "iPad, Android tablets, and other tablets",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "brand",
            fieldType: "select",
            label: "Brand",
            required: true,
            options: ["Apple", "Samsung", "Huawei", "Lenovo", "Tecno", "Other"],
          },
          {
            fieldName: "model",
            fieldType: "text",
            label: "Model",
            required: true,
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
          {
            fieldName: "screenSize",
            fieldType: "text",
            label: "Screen Size",
            placeholder: "e.g. 10.9 inch",
          },
        ],
      },
      {
        name: "Laptops & Computers",
        slug: "laptops-computers",
        description: "Laptops, desktops, and computer accessories",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Laptop", "Desktop", "All-in-One"],
          },
          {
            fieldName: "brand",
            fieldType: "select",
            label: "Brand",
            required: true,
            options: [
              "Dell",
              "HP",
              "Lenovo",
              "Asus",
              "Acer",
              "Apple",
              "MSI",
              "Toshiba",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
          {
            fieldName: "processor",
            fieldType: "text",
            label: "Processor",
            placeholder: "e.g. Intel i5 10th Gen",
          },
          {
            fieldName: "ram",
            fieldType: "select",
            label: "RAM",
            options: ["4GB", "8GB", "16GB", "32GB", "64GB"],
          },
        ],
      },
      {
        name: "TVs & Audio",
        slug: "tvs-audio",
        description: "Televisions, speakers, and audio equipment",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Television", "Speaker", "Headphones", "Sound System"],
          },
          {
            fieldName: "brand",
            fieldType: "select",
            label: "Brand",
            options: [
              "Samsung",
              "LG",
              "Sony",
              "TCL",
              "Hisense",
              "JBL",
              "Bose",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
        ],
      },
      {
        name: "Accessories",
        slug: "accessories",
        description: "Chargers, cables, cases, and other accessories",
        isActive: true,
        sortOrder: 5,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: [
              "Charger",
              "Cable",
              "Case",
              "Screen Protector",
              "Power Bank",
              "Memory Card",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
        ],
      },
    ],
  },
  {
    name: "Vehicles",
    slug: "vehicles",
    icon: "🚗",
    description: "Cars, motorcycles, and automotive parts",
    sortOrder: 2,
    isActive: true,
    subcategories: [
      {
        name: "Cars",
        slug: "cars",
        description: "Passenger cars and SUVs",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "make",
            fieldType: "select",
            label: "Make",
            required: true,
            options: [
              "Toyota",
              "Honda",
              "Nissan",
              "Mazda",
              "Ford",
              "Hyundai",
              "Kia",
              "Chevrolet",
              "Mercedes-Benz",
              "BMW",
              "Audi",
              "Volkswagen",
              "Other",
            ],
          },
          {
            fieldName: "model",
            fieldType: "text",
            label: "Model",
            required: true,
            placeholder: "e.g. Camry, Accord, Altima",
          },
          {
            fieldName: "year",
            fieldType: "number",
            label: "Year",
            required: true,
            validation: {
              min: 1990,
              max: new Date().getFullYear() + 1,
            },
          },
          {
            fieldName: "mileage",
            fieldType: "number",
            label: "Mileage (miles)",
            placeholder: "e.g. 50000",
          },
          {
            fieldName: "fuelType",
            fieldType: "select",
            label: "Fuel Type",
            options: ["Gasoline", "Diesel", "Hybrid", "Electric"],
          },
          {
            fieldName: "transmission",
            fieldType: "select",
            label: "Transmission",
            options: ["Manual", "Automatic", "CVT"],
          },
          {
            fieldName: "color",
            fieldType: "text",
            label: "Color",
            placeholder: "e.g. White, Black, Silver",
          },
        ],
      },
      {
        name: "Motorcycles",
        slug: "motorcycles",
        description: "Motorcycles and scooters",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "make",
            fieldType: "select",
            label: "Make",
            required: true,
            options: [
              "Honda",
              "Yamaha",
              "Suzuki",
              "Kawasaki",
              "TVS",
              "Bajaj",
              "Other",
            ],
          },
          {
            fieldName: "model",
            fieldType: "text",
            label: "Model",
            required: true,
          },
          {
            fieldName: "year",
            fieldType: "number",
            label: "Year",
            required: true,
            validation: {
              min: 1990,
              max: new Date().getFullYear() + 1,
            },
          },
          {
            fieldName: "engineSize",
            fieldType: "text",
            label: "Engine Size (cc)",
            placeholder: "e.g. 150cc, 250cc",
          },
        ],
      },
      {
        name: "Auto Parts",
        slug: "auto-parts",
        description: "Car and motorcycle parts and accessories",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "partType",
            fieldType: "select",
            label: "Part Type",
            required: true,
            options: [
              "Engine Parts",
              "Body Parts",
              "Interior",
              "Tires",
              "Electronics",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Used - Good", "Used - Fair", "For Parts"],
          },
        ],
      },
    ],
  },
  {
    name: "Fashion & Beauty",
    slug: "fashion-beauty",
    icon: "👗",
    description: "Clothing, shoes, accessories, and beauty products",
    sortOrder: 3,
    isActive: true,
    subcategories: [
      {
        name: "Men's Fashion",
        slug: "mens-fashion",
        description: "Men's clothing and accessories",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Shirts",
              "Pants",
              "Shoes",
              "Suits",
              "Casual Wear",
              "Underwear",
              "Accessories",
            ],
          },
          {
            fieldName: "size",
            fieldType: "select",
            label: "Size",
            options: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Women's Fashion",
        slug: "womens-fashion",
        description: "Women's clothing and accessories",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Dresses",
              "Tops",
              "Bottoms",
              "Shoes",
              "Bags",
              "Jewelry",
              "Underwear",
              "Accessories",
            ],
          },
          {
            fieldName: "size",
            fieldType: "select",
            label: "Size",
            options: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Children's Fashion",
        slug: "childrens-fashion",
        description: "Children's clothing and accessories",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "ageGroup",
            fieldType: "select",
            label: "Age Group",
            required: true,
            options: [
              "0-12 months",
              "1-2 years",
              "3-4 years",
              "5-7 years",
              "8-12 years",
              "13+ years",
            ],
          },
          {
            fieldName: "gender",
            fieldType: "select",
            label: "Gender",
            options: ["Boys", "Girls", "Unisex"],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Beauty & Personal Care",
        slug: "beauty-personal-care",
        description: "Cosmetics, skincare, and personal care products",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Skincare",
              "Makeup",
              "Hair Care",
              "Fragrance",
              "Personal Care",
              "Tools & Accessories",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Opened/Unused", "Gently Used"],
          },
        ],
      },
    ],
  },
  {
    name: "Home & Garden",
    slug: "home-garden",
    icon: "🏠",
    description: "Furniture, appliances, and home improvement items",
    sortOrder: 4,
    isActive: true,
    subcategories: [
      {
        name: "Furniture",
        slug: "furniture",
        description: "Indoor and outdoor furniture",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: [
              "Bedroom",
              "Living Room",
              "Dining Room",
              "Office",
              "Outdoor",
              "Storage",
            ],
          },
          {
            fieldName: "material",
            fieldType: "select",
            label: "Material",
            options: [
              "Wood",
              "Metal",
              "Plastic",
              "Glass",
              "Fabric",
              "Leather",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
        ],
      },
      {
        name: "Appliances",
        slug: "appliances",
        description: "Kitchen and home appliances",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: [
              "Refrigerator",
              "Washing Machine",
              "Microwave",
              "Air Conditioner",
              "Stove",
              "Small Appliances",
            ],
          },
          {
            fieldName: "brand",
            fieldType: "text",
            label: "Brand",
            placeholder: "e.g. Samsung, LG, Whirlpool",
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
        ],
      },
      {
        name: "Home Decor",
        slug: "home-decor",
        description: "Decorative items and home accessories",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Wall Art",
              "Lighting",
              "Rugs & Carpets",
              "Curtains",
              "Plants",
              "Decorative Objects",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Garden & Outdoor",
        slug: "garden-outdoor",
        description: "Garden tools, plants, and outdoor equipment",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Plants",
              "Tools",
              "Outdoor Furniture",
              "BBQ & Grills",
              "Garden Supplies",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
        ],
      },
    ],
  },
  {
    name: "Real Estate",
    slug: "real-estate",
    icon: "🏘️",
    description: "Houses, apartments, and commercial properties",
    sortOrder: 5,
    isActive: true,
    subcategories: [
      {
        name: "Houses for Sale",
        slug: "houses-for-sale",
        description: "Residential houses for purchase",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "bedrooms",
            fieldType: "select",
            label: "Bedrooms",
            required: true,
            options: ["1", "2", "3", "4", "5+"],
          },
          {
            fieldName: "bathrooms",
            fieldType: "select",
            label: "Bathrooms",
            required: true,
            options: ["1", "1.5", "2", "2.5", "3", "3.5", "4+"],
          },
          {
            fieldName: "area",
            fieldType: "number",
            label: "Area (sq ft)",
            placeholder: "e.g. 1200",
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Monrovia, Sinkor",
          },
        ],
      },
      {
        name: "Houses for Rent",
        slug: "houses-for-rent",
        description: "Residential houses for rental",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "bedrooms",
            fieldType: "select",
            label: "Bedrooms",
            required: true,
            options: ["1", "2", "3", "4", "5+"],
          },
          {
            fieldName: "bathrooms",
            fieldType: "select",
            label: "Bathrooms",
            required: true,
            options: ["1", "1.5", "2", "2.5", "3", "3.5", "4+"],
          },
          {
            fieldName: "furnished",
            fieldType: "select",
            label: "Furnished",
            options: ["Furnished", "Semi-Furnished", "Unfurnished"],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Monrovia, Sinkor",
          },
        ],
      },
      {
        name: "Apartments",
        slug: "apartments",
        description: "Apartment rentals and sales",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["For Sale", "For Rent"],
          },
          {
            fieldName: "bedrooms",
            fieldType: "select",
            label: "Bedrooms",
            required: true,
            options: ["Studio", "1", "2", "3", "4+"],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Monrovia, Sinkor",
          },
        ],
      },
      {
        name: "Commercial Property",
        slug: "commercial-property",
        description: "Offices, shops, and commercial spaces",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Office", "Shop", "Warehouse", "Restaurant", "Other"],
          },
          {
            fieldName: "purpose",
            fieldType: "select",
            label: "Purpose",
            required: true,
            options: ["For Sale", "For Rent"],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Downtown Monrovia",
          },
        ],
      },
      {
        name: "Land",
        slug: "land",
        description: "Land plots and lots for sale",
        isActive: true,
        sortOrder: 5,
        customFields: [
          {
            fieldName: "area",
            fieldType: "text",
            label: "Area",
            required: true,
            placeholder: "e.g. 0.5 acres, 1000 sq ft",
          },
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            options: ["Residential", "Commercial", "Agricultural", "Mixed Use"],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Paynesville, Buchanan",
          },
        ],
      },
    ],
  },
  {
    name: "Jobs",
    slug: "jobs",
    icon: "💼",
    description: "Job opportunities and career listings",
    sortOrder: 6,
    isActive: true,
    subcategories: [
      {
        name: "Full-time Jobs",
        slug: "full-time-jobs",
        description: "Full-time employment opportunities",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "industry",
            fieldType: "select",
            label: "Industry",
            required: true,
            options: [
              "Technology",
              "Banking & Finance",
              "Healthcare",
              "Education",
              "NGO/Non-Profit",
              "Government",
              "Mining",
              "Agriculture",
              "Construction",
              "Retail",
              "Hospitality",
              "Other",
            ],
          },
          {
            fieldName: "experienceLevel",
            fieldType: "select",
            label: "Experience Level",
            required: true,
            options: ["Entry Level", "Mid Level", "Senior Level", "Executive"],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Monrovia, Gbarnga",
          },
        ],
      },
      {
        name: "Part-time Jobs",
        slug: "part-time-jobs",
        description: "Part-time and flexible work opportunities",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "industry",
            fieldType: "select",
            label: "Industry",
            required: true,
            options: [
              "Retail",
              "Hospitality",
              "Education",
              "Customer Service",
              "Data Entry",
              "Sales",
              "Other",
            ],
          },
          {
            fieldName: "hoursPerWeek",
            fieldType: "select",
            label: "Hours per Week",
            options: ["Less than 10", "10-20", "20-30", "Flexible"],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Monrovia, Remote",
          },
        ],
      },
      {
        name: "Freelance & Contract",
        slug: "freelance-contract",
        description: "Freelance and contract work opportunities",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Web Development",
              "Graphic Design",
              "Writing & Translation",
              "Marketing",
              "Consulting",
              "Photography",
              "Other",
            ],
          },
          {
            fieldName: "projectDuration",
            fieldType: "select",
            label: "Project Duration",
            options: [
              "1-7 days",
              "1-4 weeks",
              "1-3 months",
              "3+ months",
              "Ongoing",
            ],
          },
        ],
      },
      {
        name: "Internships",
        slug: "internships",
        description: "Internship opportunities for students and graduates",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "industry",
            fieldType: "select",
            label: "Industry",
            required: true,
            options: [
              "Technology",
              "Banking & Finance",
              "Healthcare",
              "Education",
              "NGO/Non-Profit",
              "Government",
              "Media",
              "Other",
            ],
          },
          {
            fieldName: "duration",
            fieldType: "select",
            label: "Duration",
            options: ["1-3 months", "3-6 months", "6+ months"],
          },
          {
            fieldName: "paid",
            fieldType: "select",
            label: "Compensation",
            options: ["Paid", "Unpaid", "Stipend"],
          },
        ],
      },
    ],
  },
  {
    name: "Services",
    slug: "services",
    icon: "🔧",
    description: "Professional and personal services",
    sortOrder: 7,
    isActive: true,
    subcategories: [
      {
        name: "Construction & Repair",
        slug: "construction-repair",
        description: "Construction, plumbing, electrical, and repair services",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Construction",
              "Plumbing",
              "Electrical",
              "Carpentry",
              "Painting",
              "Roofing",
              "General Repair",
              "Other",
            ],
          },
          {
            fieldName: "experience",
            fieldType: "select",
            label: "Years of Experience",
            options: ["1-2 years", "3-5 years", "5-10 years", "10+ years"],
          },
        ],
      },
      {
        name: "Transportation",
        slug: "transportation",
        description: "Taxi, delivery, and transportation services",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Taxi",
              "Delivery",
              "Moving",
              "Car Rental",
              "Motorcycle Taxi",
              "Other",
            ],
          },
          {
            fieldName: "coverage",
            fieldType: "text",
            label: "Service Area",
            placeholder: "e.g. Greater Monrovia, Nationwide",
          },
        ],
      },
      {
        name: "Cleaning & Housekeeping",
        slug: "cleaning-housekeeping",
        description: "Cleaning and domestic services",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "House Cleaning",
              "Office Cleaning",
              "Laundry",
              "Gardening",
              "Security",
              "Other",
            ],
          },
          {
            fieldName: "frequency",
            fieldType: "select",
            label: "Frequency",
            options: [
              "One-time",
              "Weekly",
              "Bi-weekly",
              "Monthly",
              "As needed",
            ],
          },
        ],
      },
      {
        name: "IT & Tech Support",
        slug: "it-tech-support",
        description: "Computer repair, web development, and tech services",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Computer Repair",
              "Phone Repair",
              "Web Development",
              "Software Development",
              "Network Setup",
              "Data Recovery",
              "Other",
            ],
          },
        ],
      },
      {
        name: "Education & Tutoring",
        slug: "education-tutoring",
        description: "Private tutoring and educational services",
        isActive: true,
        sortOrder: 5,
        customFields: [
          {
            fieldName: "subject",
            fieldType: "select",
            label: "Subject",
            required: true,
            options: [
              "Mathematics",
              "English",
              "Science",
              "Computer Skills",
              "Music",
              "Language Learning",
              "Test Preparation",
              "Other",
            ],
          },
          {
            fieldName: "level",
            fieldType: "select",
            label: "Level",
            options: [
              "Elementary",
              "High School",
              "University",
              "Adult Learning",
            ],
          },
        ],
      },
      {
        name: "Health & Beauty Services",
        slug: "health-beauty-services",
        description: "Beauty salons, spas, and wellness services",
        isActive: true,
        sortOrder: 6,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Hair Salon",
              "Nail Salon",
              "Spa & Massage",
              "Makeup Services",
              "Fitness Training",
              "Health Consultation",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Food & Agriculture",
    slug: "food-agriculture",
    icon: "🌾",
    description: "Food products, farming supplies, and agricultural items",
    sortOrder: 8,
    isActive: true,
    subcategories: [
      {
        name: "Fresh Produce",
        slug: "fresh-produce",
        description: "Fruits, vegetables, and fresh farm products",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Fruits", "Vegetables", "Herbs", "Grains", "Nuts"],
          },
          {
            fieldName: "organic",
            fieldType: "select",
            label: "Organic",
            options: ["Yes", "No"],
          },
          {
            fieldName: "origin",
            fieldType: "text",
            label: "Origin/Farm Location",
            placeholder: "e.g. Bong County, Nimba",
          },
        ],
      },
      {
        name: "Livestock & Poultry",
        slug: "livestock-poultry",
        description: "Animals for farming and consumption",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "animalType",
            fieldType: "select",
            label: "Animal Type",
            required: true,
            options: [
              "Cattle",
              "Goats",
              "Sheep",
              "Pigs",
              "Chickens",
              "Ducks",
              "Fish",
            ],
          },
          {
            fieldName: "age",
            fieldType: "text",
            label: "Age",
            placeholder: "e.g. 6 months, 2 years",
          },
          {
            fieldName: "purpose",
            fieldType: "select",
            label: "Purpose",
            options: ["Breeding", "Meat", "Dairy", "Eggs", "Pet"],
          },
        ],
      },
      {
        name: "Farm Equipment",
        slug: "farm-equipment",
        description: "Agricultural tools and machinery",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "equipmentType",
            fieldType: "select",
            label: "Equipment Type",
            required: true,
            options: [
              "Hand Tools",
              "Tractors",
              "Irrigation",
              "Processing Equipment",
              "Storage",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair", "Poor"],
          },
        ],
      },
      {
        name: "Seeds & Plants",
        slug: "seeds-plants",
        description: "Seeds, seedlings, and plants for farming",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "plantType",
            fieldType: "select",
            label: "Plant Type",
            required: true,
            options: [
              "Vegetables",
              "Fruits",
              "Grains",
              "Cash Crops",
              "Ornamental",
            ],
          },
          {
            fieldName: "variety",
            fieldType: "text",
            label: "Variety",
            placeholder: "e.g. Roma Tomato, Red Rice",
          },
        ],
      },
    ],
  },
  {
    name: "Sports & Recreation",
    slug: "sports-recreation",
    icon: "⚽",
    description: "Sports equipment, fitness gear, and recreational items",
    sortOrder: 9,
    isActive: true,
    subcategories: [
      {
        name: "Fitness Equipment",
        slug: "fitness-equipment",
        description: "Gym equipment and fitness accessories",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "equipmentType",
            fieldType: "select",
            label: "Equipment Type",
            required: true,
            options: [
              "Cardio",
              "Strength Training",
              "Weights",
              "Yoga & Pilates",
              "Accessories",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Team Sports",
        slug: "team-sports",
        description:
          "Equipment for football, basketball, and other team sports",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "sport",
            fieldType: "select",
            label: "Sport",
            required: true,
            options: [
              "Football",
              "Basketball",
              "Volleyball",
              "Tennis",
              "Cricket",
              "Other",
            ],
          },
          {
            fieldName: "itemType",
            fieldType: "select",
            label: "Item Type",
            options: ["Ball", "Equipment", "Uniform", "Shoes", "Accessories"],
          },
        ],
      },
      {
        name: "Outdoor Activities",
        slug: "outdoor-activities",
        description: "Camping, fishing, and outdoor recreation gear",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "activity",
            fieldType: "select",
            label: "Activity",
            required: true,
            options: [
              "Camping",
              "Fishing",
              "Hiking",
              "Swimming",
              "Cycling",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Books & Education",
    slug: "books-education",
    icon: "📚",
    description: "Books, educational materials, and learning resources",
    sortOrder: 10,
    isActive: true,
    subcategories: [
      {
        name: "Academic Books",
        slug: "academic-books",
        description: "Textbooks and academic materials",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "level",
            fieldType: "select",
            label: "Education Level",
            required: true,
            options: [
              "Elementary",
              "Junior High",
              "Senior High",
              "University",
              "Professional",
            ],
          },
          {
            fieldName: "subject",
            fieldType: "select",
            label: "Subject",
            options: [
              "Mathematics",
              "Science",
              "English",
              "History",
              "Geography",
              "Business",
              "Medicine",
              "Law",
              "Engineering",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "General Books",
        slug: "general-books",
        description: "Fiction, non-fiction, and recreational reading",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "genre",
            fieldType: "select",
            label: "Genre",
            options: [
              "Fiction",
              "Non-Fiction",
              "Biography",
              "Self-Help",
              "Religion",
              "Children's Books",
              "Poetry",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Educational Supplies",
        slug: "educational-supplies",
        description: "School supplies and educational materials",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "itemType",
            fieldType: "select",
            label: "Item Type",
            required: true,
            options: [
              "Stationery",
              "Art Supplies",
              "Calculators",
              "Bags",
              "Uniforms",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Baby & Kids",
    slug: "baby-kids",
    icon: "👶",
    description: "Baby items, toys, and children's products",
    sortOrder: 11,
    isActive: true,
    subcategories: [
      {
        name: "Baby Care",
        slug: "baby-care",
        description: "Baby care products and essentials",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "ageGroup",
            fieldType: "select",
            label: "Age Group",
            required: true,
            options: ["0-6 months", "6-12 months", "1-2 years", "2+ years"],
          },
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Feeding",
              "Diapering",
              "Bathing",
              "Safety",
              "Health",
              "Other",
            ],
          },
        ],
      },
      {
        name: "Baby Gear",
        slug: "baby-gear",
        description: "Strollers, car seats, and baby equipment",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "gearType",
            fieldType: "select",
            label: "Gear Type",
            required: true,
            options: [
              "Stroller",
              "Car Seat",
              "High Chair",
              "Crib",
              "Baby Carrier",
              "Playpen",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Toys & Games",
        slug: "toys-games",
        description: "Toys, games, and entertainment for children",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "ageGroup",
            fieldType: "select",
            label: "Age Group",
            required: true,
            options: [
              "0-2 years",
              "3-5 years",
              "6-8 years",
              "9-12 years",
              "13+ years",
            ],
          },
          {
            fieldName: "toyType",
            fieldType: "select",
            label: "Toy Type",
            options: [
              "Educational",
              "Action Figures",
              "Dolls",
              "Building Blocks",
              "Board Games",
              "Electronic",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Pets & Animals",
    slug: "pets-animals",
    icon: "🐕",
    description: "Pets, pet supplies, and animal care products",
    sortOrder: 12,
    isActive: true,
    subcategories: [
      {
        name: "Dogs",
        slug: "dogs",
        description: "Dogs and dog-related products",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Pet for Sale", "Pet Supplies", "Pet Services"],
          },
          {
            fieldName: "breed",
            fieldType: "text",
            label: "Breed",
            placeholder: "e.g. German Shepherd, Mixed",
          },
          {
            fieldName: "age",
            fieldType: "select",
            label: "Age",
            options: [
              "Puppy (0-1 year)",
              "Young (1-3 years)",
              "Adult (3-7 years)",
              "Senior (7+ years)",
            ],
          },
        ],
      },
      {
        name: "Cats",
        slug: "cats",
        description: "Cats and cat-related products",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Pet for Sale", "Pet Supplies", "Pet Services"],
          },
          {
            fieldName: "breed",
            fieldType: "text",
            label: "Breed",
            placeholder: "e.g. Persian, Mixed",
          },
        ],
      },
      {
        name: "Other Pets",
        slug: "other-pets",
        description: "Birds, fish, and other pets",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "animalType",
            fieldType: "select",
            label: "Animal Type",
            required: true,
            options: [
              "Bird",
              "Fish",
              "Rabbit",
              "Guinea Pig",
              "Reptile",
              "Other",
            ],
          },
          {
            fieldName: "type",
            fieldType: "select",
            label: "Type",
            required: true,
            options: ["Pet for Sale", "Pet Supplies", "Pet Services"],
          },
        ],
      },
      {
        name: "Pet Services",
        slug: "pet-services",
        description: "Veterinary, grooming, and pet care services",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Veterinary",
              "Grooming",
              "Pet Sitting",
              "Training",
              "Boarding",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Health & Medical",
    slug: "health-medical",
    icon: "⚕️",
    description: "Health products, medical supplies, and wellness items",
    sortOrder: 13,
    isActive: true,
    subcategories: [
      {
        name: "Medical Equipment",
        slug: "medical-equipment",
        description: "Medical devices and equipment",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "equipmentType",
            fieldType: "select",
            label: "Equipment Type",
            required: true,
            options: [
              "Diagnostic",
              "Therapeutic",
              "Mobility Aid",
              "First Aid",
              "Monitoring",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Wellness Products",
        slug: "wellness-products",
        description: "Vitamins, supplements, and wellness items",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "productType",
            fieldType: "select",
            label: "Product Type",
            required: true,
            options: [
              "Vitamins",
              "Supplements",
              "Herbal Products",
              "Fitness Products",
              "Other",
            ],
          },
        ],
      },
      {
        name: "Personal Care",
        slug: "personal-care",
        description: "Hygiene and personal care products",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "productType",
            fieldType: "select",
            label: "Product Type",
            required: true,
            options: [
              "Oral Care",
              "Skin Care",
              "Hair Care",
              "Feminine Care",
              "Men's Care",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Arts & Entertainment",
    slug: "arts-entertainment",
    icon: "🎨",
    description: "Art supplies, musical instruments, and entertainment items",
    sortOrder: 14,
    isActive: true,
    subcategories: [
      {
        name: "Musical Instruments",
        slug: "musical-instruments",
        description: "Instruments and music equipment",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "instrumentType",
            fieldType: "select",
            label: "Instrument Type",
            required: true,
            options: [
              "Guitar",
              "Piano/Keyboard",
              "Drums",
              "Wind Instruments",
              "Traditional",
              "Audio Equipment",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Art Supplies",
        slug: "art-supplies",
        description: "Art materials and craft supplies",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "artType",
            fieldType: "select",
            label: "Art Type",
            required: true,
            options: [
              "Drawing",
              "Painting",
              "Crafts",
              "Sculpture",
              "Digital Art",
              "Calligraphy",
              "Other",
            ],
          },
        ],
      },
      {
        name: "Games & Hobbies",
        slug: "games-hobbies",
        description: "Board games, puzzles, and hobby items",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "hobbyType",
            fieldType: "select",
            label: "Hobby Type",
            required: true,
            options: [
              "Board Games",
              "Card Games",
              "Puzzles",
              "Collecting",
              "Model Building",
              "Other",
            ],
          },
        ],
      },
      {
        name: "Movies & Music",
        slug: "movies-music",
        description: "DVDs, CDs, and entertainment media",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "mediaType",
            fieldType: "select",
            label: "Media Type",
            required: true,
            options: ["DVD", "CD", "Vinyl Record", "Digital Content", "Other"],
          },
          {
            fieldName: "genre",
            fieldType: "select",
            label: "Genre",
            options: [
              "Action",
              "Comedy",
              "Drama",
              "Music",
              "Documentary",
              "Local Content",
              "Other",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Business & Industrial",
    slug: "business-industrial",
    icon: "🏭",
    description:
      "Industrial equipment, business supplies, and commercial items",
    sortOrder: 15,
    isActive: true,
    subcategories: [
      {
        name: "Office Supplies",
        slug: "office-supplies",
        description: "Office furniture, stationery, and business equipment",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Furniture",
              "Stationery",
              "Electronics",
              "Printing",
              "Storage",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Industrial Equipment",
        slug: "industrial-equipment",
        description: "Heavy machinery and industrial tools",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "equipmentType",
            fieldType: "select",
            label: "Equipment Type",
            required: true,
            options: [
              "Manufacturing",
              "Construction",
              "Mining",
              "Agriculture",
              "Transportation",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Used - Good", "Used - Fair", "For Parts"],
          },
        ],
      },
      {
        name: "Restaurant & Catering",
        slug: "restaurant-catering",
        description: "Commercial kitchen equipment and catering supplies",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "equipmentType",
            fieldType: "select",
            label: "Equipment Type",
            required: true,
            options: [
              "Cooking Equipment",
              "Refrigeration",
              "Serving",
              "Storage",
              "Cleaning",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
      {
        name: "Security & Safety",
        slug: "security-safety",
        description: "Security systems and safety equipment",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "CCTV Systems",
              "Alarms",
              "Access Control",
              "Safety Equipment",
              "Fire Safety",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
    ],
  },
  {
    name: "Travel & Tourism",
    slug: "travel-tourism",
    icon: "✈️",
    description: "Travel services, tour packages, and tourism-related items",
    sortOrder: 16,
    isActive: true,
    subcategories: [
      {
        name: "Tour Packages",
        slug: "tour-packages",
        description: "Local and international tour packages",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "tourType",
            fieldType: "select",
            label: "Tour Type",
            required: true,
            options: [
              "Cultural Tours",
              "Adventure Tours",
              "City Tours",
              "Beach Tours",
              "Historical Tours",
              "Custom Tours",
            ],
          },
          {
            fieldName: "duration",
            fieldType: "select",
            label: "Duration",
            required: true,
            options: [
              "Half Day",
              "Full Day",
              "2-3 Days",
              "1 Week",
              "2+ Weeks",
              "Custom",
            ],
          },
          {
            fieldName: "groupSize",
            fieldType: "select",
            label: "Group Size",
            options: [
              "Individual",
              "Small Group (2-6)",
              "Medium Group (7-15)",
              "Large Group (16+)",
              "Custom",
            ],
          },
        ],
      },
      {
        name: "Accommodation",
        slug: "accommodation",
        description: "Hotels, guesthouses, and short-term rentals",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "accommodationType",
            fieldType: "select",
            label: "Accommodation Type",
            required: true,
            options: [
              "Hotel",
              "Guesthouse",
              "Resort",
              "Apartment",
              "Hostel",
              "Lodge",
            ],
          },
          {
            fieldName: "amenities",
            fieldType: "select",
            label: "Key Amenities",
            options: [
              "WiFi",
              "Pool",
              "Restaurant",
              "Gym",
              "Spa",
              "Conference Room",
              "Airport Shuttle",
            ],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Monrovia, Robertsport, Sapo National Park",
          },
        ],
      },
      {
        name: "Transportation Services",
        slug: "transportation-services",
        description:
          "Airport transfers, car rentals, and travel transportation",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Airport Transfer",
              "Car Rental",
              "Bus Service",
              "Charter Service",
              "Driver Service",
            ],
          },
          {
            fieldName: "vehicleType",
            fieldType: "select",
            label: "Vehicle Type",
            options: ["Sedan", "SUV", "Minivan", "Bus", "4WD", "Motorcycle"],
          },
          {
            fieldName: "coverage",
            fieldType: "text",
            label: "Service Area",
            placeholder: "e.g. Monrovia Area, Nationwide",
          },
        ],
      },
      {
        name: "Travel Accessories",
        slug: "travel-accessories",
        description: "Luggage, travel gear, and accessories",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "category",
            fieldType: "select",
            label: "Category",
            required: true,
            options: [
              "Luggage",
              "Backpacks",
              "Travel Electronics",
              "Camping Gear",
              "Travel Clothing",
              "Other",
            ],
          },
          {
            fieldName: "condition",
            fieldType: "select",
            label: "Condition",
            required: true,
            options: ["Brand New", "Like New", "Good", "Fair"],
          },
        ],
      },
    ],
  },
  {
    name: "Community & Events",
    slug: "community-events",
    icon: "🎪",
    description: "Community services, events, and local activities",
    sortOrder: 17,
    isActive: true,
    subcategories: [
      {
        name: "Event Planning",
        slug: "event-planning",
        description:
          "Wedding planning, parties, and event organization services",
        isActive: true,
        sortOrder: 1,
        customFields: [
          {
            fieldName: "eventType",
            fieldType: "select",
            label: "Event Type",
            required: true,
            options: [
              "Wedding",
              "Birthday Party",
              "Corporate Event",
              "Conference",
              "Cultural Event",
              "Funeral",
              "Other",
            ],
          },
          {
            fieldName: "services",
            fieldType: "select",
            label: "Services Offered",
            options: [
              "Full Planning",
              "Coordination Only",
              "Venue Decoration",
              "Catering",
              "Photography",
              "Music/DJ",
            ],
          },
          {
            fieldName: "guestCapacity",
            fieldType: "select",
            label: "Guest Capacity",
            options: [
              "Small (1-25)",
              "Medium (26-100)",
              "Large (101-300)",
              "Very Large (300+)",
              "Any Size",
            ],
          },
        ],
      },
      {
        name: "Venue Rentals",
        slug: "venue-rentals",
        description: "Event venues, halls, and rental spaces",
        isActive: true,
        sortOrder: 2,
        customFields: [
          {
            fieldName: "venueType",
            fieldType: "select",
            label: "Venue Type",
            required: true,
            options: [
              "Wedding Hall",
              "Conference Center",
              "Outdoor Space",
              "Restaurant",
              "Community Center",
              "Private Home",
            ],
          },
          {
            fieldName: "capacity",
            fieldType: "select",
            label: "Capacity",
            required: true,
            options: [
              "Small (1-50)",
              "Medium (51-150)",
              "Large (151-300)",
              "Very Large (300+)",
            ],
          },
          {
            fieldName: "amenities",
            fieldType: "select",
            label: "Available Amenities",
            options: [
              "Sound System",
              "Projector",
              "Catering Kitchen",
              "Parking",
              "Air Conditioning",
              "Stage",
            ],
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Location",
            required: true,
            placeholder: "e.g. Central Monrovia, Sinkor",
          },
        ],
      },
      {
        name: "Photography & Videography",
        slug: "photography-videography",
        description: "Event photography and videography services",
        isActive: true,
        sortOrder: 3,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Photography Only",
              "Videography Only",
              "Both Photo & Video",
              "Live Streaming",
              "Drone Services",
            ],
          },
          {
            fieldName: "eventTypes",
            fieldType: "select",
            label: "Event Specialization",
            options: [
              "Weddings",
              "Corporate",
              "Portraits",
              "Products",
              "Events",
              "Real Estate",
              "All Types",
            ],
          },
          {
            fieldName: "experience",
            fieldType: "select",
            label: "Years of Experience",
            options: ["1-2 years", "3-5 years", "5-10 years", "10+ years"],
          },
        ],
      },
      {
        name: "Music & Entertainment",
        slug: "music-entertainment",
        description: "DJs, live bands, and entertainment services",
        isActive: true,
        sortOrder: 4,
        customFields: [
          {
            fieldName: "entertainmentType",
            fieldType: "select",
            label: "Entertainment Type",
            required: true,
            options: [
              "DJ Services",
              "Live Band",
              "Solo Artist",
              "Traditional Performers",
              "Comedian",
              "MC/Host",
            ],
          },
          {
            fieldName: "musicGenre",
            fieldType: "select",
            label: "Music Genre",
            options: [
              "Afrobeat",
              "Hip Hop",
              "Gospel",
              "Traditional Liberian",
              "Reggae",
              "Jazz",
              "All Genres",
            ],
          },
          {
            fieldName: "eventTypes",
            fieldType: "select",
            label: "Event Types",
            options: [
              "Weddings",
              "Parties",
              "Corporate Events",
              "Clubs",
              "Festivals",
              "All Events",
            ],
          },
        ],
      },
      {
        name: "Community Services",
        slug: "community-services",
        description: "Local community services and volunteer opportunities",
        isActive: true,
        sortOrder: 5,
        customFields: [
          {
            fieldName: "serviceType",
            fieldType: "select",
            label: "Service Type",
            required: true,
            options: [
              "Volunteer Work",
              "Community Outreach",
              "Religious Services",
              "Cultural Programs",
              "Youth Programs",
              "Elder Care",
            ],
          },
          {
            fieldName: "organization",
            fieldType: "text",
            label: "Organization",
            placeholder: "e.g. Local NGO, Church, Community Group",
          },
          {
            fieldName: "location",
            fieldType: "text",
            label: "Service Area",
            required: true,
            placeholder: "e.g. Greater Monrovia, Bong County",
          },
        ],
      },
    ],
  },
];

async function seedCategories() {
  try {
    // Load environment variables
    require("dotenv").config();

    // Use the EXACT same connection as the API routes - no database name modification
    const mongoUri =
      process.env.MONGODB_URI || "mongodb://localhost:27017/buysell";

    await mongoose.connect(mongoUri, {
      serverSelectionTimeoutMS: 5000,
    });
    console.log("✅ Connected to MongoDB (same as API routes)");
    console.log("🔗 Database:", mongoose.connection.name);
    console.log("🌐 Host:", mongoose.connection.host);
    console.log(
      "📍 URI pattern:",
      mongoUri.includes("mongodb+srv://") ? "Atlas Cloud" : "Local"
    );

    // Clear existing categories
    await Category.deleteMany({});
    console.log("🗑️ Cleared existing categories");

    // Insert new categories
    const categories = await Category.insertMany(initialCategories);
    console.log(`🌱 Successfully seeded ${categories.length} categories`);

    // Log the created categories
    categories.forEach((category) => {
      console.log(
        `   📂 ${category.name} (${category.subcategories.length} subcategories)`
      );
    });

    console.log("\n✅ Category seeding completed successfully!");
    console.log(
      "📄 All subcategories use placeholder images: /placeholder.jpg"
    );
    console.log("🚀 Ready to use in your Liberian marketplace!");

    // Verify data was saved by counting documents
    const count = await Category.countDocuments();
    console.log(`\n🔍 Verification: ${count} categories found in database`);

    if (count === 17) {
      console.log("✅ All 17 categories confirmed in database!");
    } else {
      console.log("⚠️  Warning: Expected 17 categories but found", count);
    }

    // Show first few categories as proof
    const sampleCategories = await Category.find()
      .limit(3)
      .select("name slug")
      .lean();
    console.log("\n📋 Sample categories in database:");
    sampleCategories.forEach((cat) => {
      console.log(`   - ${cat.name} (${cat.slug})`);
    });

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding categories:", error);
    process.exit(1);
  }
}

// Run the seeder if this file is executed directly
if (require.main === module) {
  seedCategories();
}

module.exports = seedCategories;
